# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f198dc166dbc299f44af3033a45162e20b8d5bff247baeec51d0126ffd3356a0efadea88c4bc8b87927ed43745eb6209976dbde4108994d52f4719beb4c44ce7

test:
  secret_key_base: b936a7b1cebe56b435308e1ac582788f9272de060ced3ce267268ea70342d128993c7b910db1c268d12400d992d09330a8ab7c93dfe68456a3a4df32bb174ec2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
